import type { Config } from "./_types";

export const config: Config = {
  ".git": "ignore",
  ".github": "error",
  ".husky": "ignore",
  ".next": "ignore",
  ".qodo": "ignore",
  context: "error",
  drizzle: "ignore",
  node_modules: "ignore",
  public: "ignore",
  scripts: "error",
  src: {
    app: "error",
    features: "error",
    services: "error",
    shared: {
      api: "error",
      config: "ok",
      lib: {
        auth: "error",
        "css.ts": "ok",
        "id.ts": "ok",
        "react.ts": "error",
        "s3.ts": "error",
        "timing.ts": "error",
        "transliterate.ts": "error",
      },
      ui: "error",
    },
    "proxy.ts": "error",
  },
  ".dockerignore": "ok",
  ".env.development": "ok",
  ".gitattributes": "ok",
  ".gitignore": "ok",
  "biome.json": "ok",
  "bun.lock": "ignore",
  "components.json": "ok",
  "docker-compose.yml": "ok",
  Dockerfile: "ok",
  "drizzle.config.ts": "ok",
  "next-env.d.ts": "ok",
  "next.config.ts": "ok",
  "package.json": "error",
  "postcss.config.mjs": "ok",
  "tsconfig.json": "ok",
  "tsconfig.tsbuildinfo": "ignore",
} as const;
