// apps/api/src/features/secret-voicer/voice/lib/mock-data.ts

import type { ExternalVoice } from "../data/types";

export const MOCK_VOICES: ExternalVoice[] = [
  {
    id: 1,
    voice_id: "mock-voice-adam",
    name: "Adam (Mock)",
    gender: "MALE",
    locale: "en-US",
    is_multilingual: true,
    preview_url: null,
    preview_url_emotional: null,
    usage_count: 1000,
    avatar_url: null,
    description: "A warm and friendly male voice",
    accent: "American",
    age_group: "young-adult",
    voice_style_tags: ["friendly", "warm", "conversational"],
    use_cases: ["narration", "podcasts", "audiobooks"],
  },
  {
    id: 2,
    voice_id: "mock-voice-bella",
    name: "Bella (Mock)",
    gender: "FEMALE",
    locale: "en-US",
    is_multilingual: true,
    preview_url: null,
    preview_url_emotional: null,
    usage_count: 800,
    avatar_url: null,
    description: "A bright and energetic female voice",
    accent: "American",
    age_group: "young-adult",
    voice_style_tags: ["energetic", "bright", "upbeat"],
    use_cases: ["commercials", "explainers", "social-media"],
  },
  {
    id: 3,
    voice_id: "mock-voice-charlie",
    name: "Charlie (Mock)",
    gender: "MALE",
    locale: "en-GB",
    is_multilingual: false,
    preview_url: null,
    preview_url_emotional: null,
    usage_count: 500,
    avatar_url: null,
    description: "A deep and authoritative British voice",
    accent: "British",
    age_group: "middle-aged",
    voice_style_tags: ["authoritative", "deep", "professional"],
    use_cases: ["documentaries", "corporate", "training"],
  },
];
