export const AUDIO_PROCESSING_CONSTANTS = {
  MAX_FILE_SIZE_MB: 500,
  MAX_TOTAL_SIZE_MB: 2000,
  SUPPORTED_FORMATS: [".mp3", ".wav"] as const,

  // Default settings
  DEFAULT_SILENCE_THRESHOLD: -40,
  DEFAULT_MIN_SILENCE_DURATION: 0.5,
  DEFAULT_PAUSE_BETWEEN_CHUNKS: 0.3,
  DEFAULT_PAUSE_BETWEEN_FILES: 1.0,
  DEFAULT_PAUSE_AT_START: 0.5,
  DEFAULT_PAUSE_AT_END: 0.5,
  DEFAULT_OUTPUT_FORMAT: "mp3" as const,
} as const;
