/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as PublicRouteImport } from './app/routes/_public'
import { Route as PrivateRouteImport } from './app/routes/_private'
import { Route as PublicLoginRouteImport } from './app/routes/_public/login'
import { Route as PrivateUsersRouteImport } from './app/routes/_private/users'
import { Route as PrivateSettingsRouteImport } from './app/routes/_private/settings'
import { Route as PrivateDashboardRouteImport } from './app/routes/_private/dashboard'
import { Route as PrivateUsersIndexRouteImport } from './app/routes/_private/users/index'
import { Route as PrivateUsersUserIdRouteImport } from './app/routes/_private/users/$userId'
import { Route as PrivateSettingsSessionsRouteImport } from './app/routes/_private/settings/sessions'
import { Route as PrivateSettingsProvidersRouteImport } from './app/routes/_private/settings/providers'
import { Route as PrivateSettingsProfileRouteImport } from './app/routes/_private/settings/profile'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PrivateUsersRoute = PrivateUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateSettingsRoute = PrivateSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateDashboardRoute = PrivateDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateUsersIndexRoute = PrivateUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateUsersRoute,
} as any)
const PrivateUsersUserIdRoute = PrivateUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => PrivateUsersRoute,
} as any)
const PrivateSettingsSessionsRoute = PrivateSettingsSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => PrivateSettingsRoute,
} as any)
const PrivateSettingsProvidersRoute =
  PrivateSettingsProvidersRouteImport.update({
    id: '/providers',
    path: '/providers',
    getParentRoute: () => PrivateSettingsRoute,
  } as any)
const PrivateSettingsProfileRoute = PrivateSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PrivateSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicRouteWithChildren
  '/dashboard': typeof PrivateDashboardRoute
  '/settings': typeof PrivateSettingsRouteWithChildren
  '/users': typeof PrivateUsersRouteWithChildren
  '/login': typeof PublicLoginRoute
  '/settings/profile': typeof PrivateSettingsProfileRoute
  '/settings/providers': typeof PrivateSettingsProvidersRoute
  '/settings/sessions': typeof PrivateSettingsSessionsRoute
  '/users/$userId': typeof PrivateUsersUserIdRoute
  '/users/': typeof PrivateUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicRouteWithChildren
  '/dashboard': typeof PrivateDashboardRoute
  '/settings': typeof PrivateSettingsRouteWithChildren
  '/login': typeof PublicLoginRoute
  '/settings/profile': typeof PrivateSettingsProfileRoute
  '/settings/providers': typeof PrivateSettingsProvidersRoute
  '/settings/sessions': typeof PrivateSettingsSessionsRoute
  '/users/$userId': typeof PrivateUsersUserIdRoute
  '/users': typeof PrivateUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_private/dashboard': typeof PrivateDashboardRoute
  '/_private/settings': typeof PrivateSettingsRouteWithChildren
  '/_private/users': typeof PrivateUsersRouteWithChildren
  '/_public/login': typeof PublicLoginRoute
  '/_private/settings/profile': typeof PrivateSettingsProfileRoute
  '/_private/settings/providers': typeof PrivateSettingsProvidersRoute
  '/_private/settings/sessions': typeof PrivateSettingsSessionsRoute
  '/_private/users/$userId': typeof PrivateUsersUserIdRoute
  '/_private/users/': typeof PrivateUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/settings'
    | '/users'
    | '/login'
    | '/settings/profile'
    | '/settings/providers'
    | '/settings/sessions'
    | '/users/$userId'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/settings'
    | '/login'
    | '/settings/profile'
    | '/settings/providers'
    | '/settings/sessions'
    | '/users/$userId'
    | '/users'
  id:
    | '__root__'
    | '/_private'
    | '/_public'
    | '/_private/dashboard'
    | '/_private/settings'
    | '/_private/users'
    | '/_public/login'
    | '/_private/settings/profile'
    | '/_private/settings/providers'
    | '/_private/settings/sessions'
    | '/_private/users/$userId'
    | '/_private/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRoute: typeof PrivateRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_private/users': {
      id: '/_private/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof PrivateUsersRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/settings': {
      id: '/_private/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof PrivateSettingsRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/dashboard': {
      id: '/_private/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PrivateDashboardRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/users/': {
      id: '/_private/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof PrivateUsersIndexRouteImport
      parentRoute: typeof PrivateUsersRoute
    }
    '/_private/users/$userId': {
      id: '/_private/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof PrivateUsersUserIdRouteImport
      parentRoute: typeof PrivateUsersRoute
    }
    '/_private/settings/sessions': {
      id: '/_private/settings/sessions'
      path: '/sessions'
      fullPath: '/settings/sessions'
      preLoaderRoute: typeof PrivateSettingsSessionsRouteImport
      parentRoute: typeof PrivateSettingsRoute
    }
    '/_private/settings/providers': {
      id: '/_private/settings/providers'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof PrivateSettingsProvidersRouteImport
      parentRoute: typeof PrivateSettingsRoute
    }
    '/_private/settings/profile': {
      id: '/_private/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof PrivateSettingsProfileRouteImport
      parentRoute: typeof PrivateSettingsRoute
    }
  }
}

interface PrivateSettingsRouteChildren {
  PrivateSettingsProfileRoute: typeof PrivateSettingsProfileRoute
  PrivateSettingsProvidersRoute: typeof PrivateSettingsProvidersRoute
  PrivateSettingsSessionsRoute: typeof PrivateSettingsSessionsRoute
}

const PrivateSettingsRouteChildren: PrivateSettingsRouteChildren = {
  PrivateSettingsProfileRoute: PrivateSettingsProfileRoute,
  PrivateSettingsProvidersRoute: PrivateSettingsProvidersRoute,
  PrivateSettingsSessionsRoute: PrivateSettingsSessionsRoute,
}

const PrivateSettingsRouteWithChildren = PrivateSettingsRoute._addFileChildren(
  PrivateSettingsRouteChildren,
)

interface PrivateUsersRouteChildren {
  PrivateUsersUserIdRoute: typeof PrivateUsersUserIdRoute
  PrivateUsersIndexRoute: typeof PrivateUsersIndexRoute
}

const PrivateUsersRouteChildren: PrivateUsersRouteChildren = {
  PrivateUsersUserIdRoute: PrivateUsersUserIdRoute,
  PrivateUsersIndexRoute: PrivateUsersIndexRoute,
}

const PrivateUsersRouteWithChildren = PrivateUsersRoute._addFileChildren(
  PrivateUsersRouteChildren,
)

interface PrivateRouteChildren {
  PrivateDashboardRoute: typeof PrivateDashboardRoute
  PrivateSettingsRoute: typeof PrivateSettingsRouteWithChildren
  PrivateUsersRoute: typeof PrivateUsersRouteWithChildren
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateDashboardRoute: PrivateDashboardRoute,
  PrivateSettingsRoute: PrivateSettingsRouteWithChildren,
  PrivateUsersRoute: PrivateUsersRouteWithChildren,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PrivateRoute: PrivateRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
