const DIALOG_DATA_TESTID = "Dialog";
const DIALOG_BACKDROP_DATA_TESTID = "DialogBackdrop";
const DIALOG_HEADER_DATA_TESTID = "DialogHeader";
const DIALOG_CONTENT_DATA_TESTID = "DialogContent";
const DIALOG_FOOTER_DATA_TESTID = "DialogFooter";

export {
  DIALOG_BACKDROP_DATA_TESTID,
  DIALOG_CONTENT_DATA_TESTID,
  DIALOG_DATA_TESTID,
  DIALOG_FOOTER_DATA_TESTID,
  DIALOG_HEADER_DATA_TESTID,
};
